easy_admin:
    entities:
        Partners:
            class: App\Entity\Partners
            controller: App\Controller\PartnersController
            form:
                title: Ajouter/Modifier un partenaire
                fields:
                    - {property: 'username'}
                    - {property: 'email'}
            list:
              max_results: 8
              fields:
                - {property: 'username', label: 'Nom'}
                - {property: 'Email'}
                - {property: 'createdAt', label: 'Date de création'}
                - {property: 'statusConfirmed', label: 'Statut'}
                - {property: 'clients'}

              item_permission: 'ROLE_ADMIN'
              actions:
                - {name: 'show',icon: 'eye', label: false, css_class: 'btn btn-primary'}
                - {name: 'edit',icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: 'delete',icon: 'trash', label: false, css_class: 'btn btn-danger'}
          