easy_admin:
    entities:
        Products:
            class: App\Entity\Products
            controller: App\Controller\ProductsController
            form:
              title: Ajouter/Modifier un produit
              fields:
                - {property: 'name'}
                - {property: 'content'}
                - {property: 'price'}
            list:
              fields:
                - {property: 'name', label: 'nom'}
                - {property: 'content', label: 'description'}
                - {property: 'price', label: 'prix'}
              actions:
                - {name: 'edit',icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: 'delete',icon: 'trash', label: false, css_class: 'btn btn-danger'}