easy_admin:
    entities:
        Products:
            class: App\Entity\Products
            controller: App\Controller\ProductsController
            form:
              title: Ajouter/Modifier un produit
              fields:
                - {property: 'name'}
                - {property: 'content'}
                - {property: 'price'}
            list:
              max_results: 8
              fields:
                - {property: 'name', label: 'Nom'}
                - {property: 'content', label: 'Description'}
                - {property: 'price', label: 'Prix'}
              actions:
                - {name: 'show',icon: 'eye', label: false, css_class: 'btn btn-primary'}
                - {name: 'edit',icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: 'delete',icon: 'trash', label: false, css_class: 'btn btn-danger'}