api_platform:
    resource: .
    type: api_platform
    prefix: /api

app_swagger_ui:
    path: /api/documentation
    methods: GET
    controller: api_platform.swagger.action.ui


authentication_token:
    path:     /authentication_token
    methods:  ['POST']